### ISSUE TITLE
内容文本首行是章节名

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#10]
https://read.qidian.com/chapter/7dpRLhU1ECN1C4AOuV6yIg2/6h_3YyTuiW2aGfXRMrUjdw2/
![图片](https://user-images.githubusercontent.com/9822709/172044864-a58a6ad5-38e4-4edf-ab6b-eadc19e180f8.png)

原文本内容, 第一行就是标题. 现在还有没有过滤首行章节名的功能, 我记得以前是有的.

**Comment by 821938089** [comment]
有这个功能，但是这种标题不符合过滤条件
![image](https://user-images.githubusercontent.com/8674809/172045346-30195685-e7b0-4f64-8189-eb74bb583e64.png)
该标题无法匹配这个正则

**Comment by letterk** [comment]
这个处理方式不太好, 应该是标题和首行去除空格相比较才是

**Comment by 821938089** [comment]
修改了一下标题去除逻辑，已经可以去掉首行标题了
脚本已更新
