### ISSUE TITLE
内容标准化

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#14]
https://www.ibiquge.net/152_152132/59655185.html

![图片](https://user-images.githubusercontent.com/9822709/174122447-a35d172c-e571-4fbb-a85b-15d0ce096217.png)

![图片](https://user-images.githubusercontent.com/9822709/174121993-2ff3bb29-c953-4ac1-a9a1-a8ee0e00f7cf.png)

**Comment by letterk** [comment]
![图片](https://user-images.githubusercontent.com/9822709/174127202-657e8d68-fb3f-4e2f-b489-781aa38edf0b.png)
原网页div是在内容结尾的

**Comment by letterk** [comment]
原网页
![图片](https://user-images.githubusercontent.com/9822709/174127679-b32a52e7-3c95-47eb-9337-056b61723fdb.png)

**Comment by 821938089** [comment]
试着修复了一下，你试试看怎么样

**Comment by letterk** [comment]
![图片](https://user-images.githubusercontent.com/9822709/174248373-71f08073-3c4f-40ca-af4d-8fcc5f13110e.png)
只能说针对这个页面现在显示是正常了, 但是html里div依然不知道什么原因位置被挪上来了

**Comment by 821938089** [comment]
忽然想到好像不能这么处理，那个广告元素就不要管他了

**Comment by 821938089** [comment]
小问题还是尽量利用站点规则来解决吧，想要弄好实在是太费劲了...
搞不动了

**Comment by letterk** [comment]
我提这个问题本来是想说, 怎么在后面的div元素会插到正文中间来. 
勾选"内容标准化"后出现问题.
取消勾选"内容标准化"就没有问题.

也怪我没有描述清楚, 让你找错方向了. 

回滚到昨天的7.1.8, 经过排查, 是`replaceNormalize.js`里的这段产生的错误
```js
// 将一段中的含多个句号、感叹号、问号的句子每句分为多段
 '([。！？])([\\u4e00-\\u9fa5“，]{20,})': '$1\n$2',
```

**Comment by 821938089** [comment]
> 我提这个问题本来是想说, 怎么在后面的div元素会插到正文中间来.

这个问题是内容处理导致的，其实相对来说这个div并没有“插到正文中间”，而是在“原位”。

当初在设计内容处理的时候，想法是将文档中的文本节点全部取出来，然后用换行符拼接到一起，然后对内容进行处理，接着再切割回去将内容写回到文本节点里面。

当时想着文本位置和文本节点是可以一一对应的。

但是后来我发现这并不一定会一一对应的，因为对内容处理会使文本多几行或少几行。

现在这个问题就是因为要进行**内容标准化**处理，会对内容进行**分段处理**，会多几行出来，导致**文本节点和内容对不上**。

但是内容处理还是按照一一对应来处理，但是**多出来的没有文本节点对应**，就只能自己创建p元素把内容写在里面，所以div元素并没有插到正文中间，而是我在父节点插入了新的p元素，**新的p是插在最底下的**，所以会在出现div下面。

这种处理还会因为实际的文本节点已经对应不上，导致**内容出现在广告元素里面**，也就是你图中的文本前面有一段不正常的空白。

内容处理部分代码：https://github.com/821938089/MyNovelReader/blob/33105000fa1b7b9325ade8ee96c7e9bb391c78be/src/MyNovelReader/parser.js#L612-L763

**Comment by letterk** [comment]
有个这样的想法, 能不能把旧的文本节点都弃用, 全删掉, 再把最终处理后的文本给添加上去.

**Comment by 821938089** [comment]
可以，换了个内容处理方式，应该不会再出问题了
