### ISSUE TITLE
晋江VIP章节缺字

### ISSUE THREAD

**Issue by piedfallow** [821938089/MyNovelReader#18]
如题，反爬字体无法被显示(显示为奇怪的图示)，如同一开始晋江所使用的反爬

**Comment by 821938089** [comment]
这个反爬字体替换是用 yingziwu 大佬写的[小说下载器](https://github.com/404-novel-project/novel-downloader)提供的服务器来在线下载替换表的，现在他的服务器出问题了，下载字体对照表返回404，需要等待他的修复才能用。

他的项目相关issue：https://github.com/404-novel-project/novel-downloader/issues/268

**Comment by piedfallow** [comment]
了解，谢谢，那我会继续等待，谢谢，我先把这个问题关闭了
