### ISSUE TITLE
怎么改ui

### ISSUE THREAD

**Issue by ublock-ghost** [821938089/MyNovelReader#19]
自带的绿色不太好看，我想换个色，自定义样式那要怎么改啊

**Comment by 821938089** [comment]
设置里面有个选择框可以换别的皮肤
![image](https://user-images.githubusercontent.com/8674809/180433512-f00317ba-6d98-4c20-8ba6-f1b3a5e65166.png)

自定义样式可以参考这里，就是写个css样式
https://github.com/821938089/MyNovelReader/blob/bd8688dd07b449630cbd72b1933a2c60f90f764e/src/MyNovelReader/UI.js#L546-L571

**Comment by ublock-ghost** [comment]
谢谢
