### ISSUE TITLE
没想到这个脚本还有人接手

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#2]
在`ywzhaiqi`停更的一两年前就听他说过好几次, 他已经不看小说了, 最后终于还是到了那一天
已经习惯了MyNovelReader, 不花哨, 专注阅读
甚至担心那一天会大规模失效, 给阅读写了个简单的前端来作为中间层给MyNovelReader使用

**Comment by 821938089** [comment]
我也是习惯了这个脚本，电脑阅读用这个脚本，手机阅读用开源阅读，简直完美。
这个脚本有类似于阅读的书源规则的站点规则，理论上只要互联网上的笔趣阁不死，这个脚本就能一直用下去。
这个脚本还有自动规则，可以通杀大多数笔趣阁模板，你可以手动给脚本添加用户包括网址就能启用脚本了。
![image](https://user-images.githubusercontent.com/8674809/168591673-12077282-e0e4-4b77-9f5f-f155f3e0af46.png)

**Comment by letterk** [comment]
其实哪怕笔趣阁死了也不怕, 因为通用规则不能用了, 单独写个规则也能用
另外有些网站在内容里插广告, 很脏, 需要过下正则. 尤其是uu看书, 我都写了好多条正则了, 还源源不断有新的广告.

**Comment by 821938089** [comment]
uu看书有些书抓取的源站点不太行，巨多广告，抓取后的过滤也不行，老是会剩一些广告的头尾，遇到这样的书换别的站点看会好一些。
你遇到的广告可以发一些链接给我看看，我加到脚本里面过滤掉。

**Comment by letterk** [comment]
uu是我找到的唯一有分卷的, 我就是看中这个才用UU看的

**Comment by 821938089** [comment]
没事的话我就关了哈，有事再开一个新的issue
