### ISSUE TITLE
其他脚本的 setTimeout 函数失效

### ISSUE THREAD

**Issue by maijz128** [821938089/MyNovelReader#22]
使用这个脚本会令其他脚本的 setTimeout、setInterval 函数失效。
原脚本却不会。

**Comment by 821938089** [comment]
该脚本在进入阅读模式的时候会把网页上的全部事件都清理掉，所以基本不能与其他脚本共存。
你要和哪个脚本一起用？

https://github.com/821938089/MyNovelReader/blob/6a7e16bdc99c2727a009782b506ccdeef937dbd2/src/MyNovelReader/inject.js#L52-L67
