### ISSUE TITLE
提前预读上一页?

### ISSUE THREAD

**Issue by etybgm** [821938089/MyNovelReader#23]
不知道github有新版本、一直在用greasyfork的6.4.3
感到最大的不同是
7.44 上一頁 MyNovelReader->原頁面(同按右下"退出"頁面)->MyNovelReader
6.43 上一頁 一直維持在MyNovelReader頁面
兩個花的時間差不多，但7.44這樣flash會感到delay很重
PRELOADER: true,                // 提前预读下一页
下一頁是無縫delay0、上一頁需delay0.5~2sec
希望大大新增這功能『提前预读上一页』

另最快的是xbyuan、不過有假章節 
7.44要改一下
      {siteName: '精华书阁',
          url: 'https?://(?:www|m).?(?:2ksk|jhssd|xbyuan).com.+?\.html',
          exampleUrl: 'https://www.jhssd.com/172/652.html',
checkSection: true,
          contentSelector: '#nr_content, #hp_coonten, #jb_contsen, #nr1',
        indexSelector: '#mulu, #pb_mulu',
        prevSelector: '#preurl, #pb_prev',
        nextSelector: "a[id='nexturl'], a:contains('下一页'), li:nth-of-type(3), a:contains('下一頁'), #nexturl, #pb_next",
contentReplace: "请记住本站域名.*|.*精华书阁.*|.*书签！|看《.+?》最快更新.*|\\(本章未完.*|免费阅读：.*"
      },

**Comment by 821938089** [comment]
翻上一页的加载原理不同，这个是不能预载的
变慢是因为我的版本增加了一些代码，会等网页完全加载完成才会进入阅读模式

这个规则有什么问题吗，我试了一下，不改也能用啊

**Comment by etybgm** [comment]
上一页不能预载(load)，那有可能預讀(read)嗎？能加速一點也好

請問快速启动打开是這行改成true？
      get fastboot() {
          return GM_getValue('fastboot', false)


加兩個輕小說站
{siteName: "ESJ",
        url: "^https?://www\\.esjzone\\.(?:me|cc)/forum/\\d+/\\d+\\.html",
        titleSelector: "h2",
        bookTitleSelector: "h2",
        contentSelector: ".mt-3.forum-content",
        indexSelector: ".view-all.btn-outline-secondary.btn",
        prevSelector: ".btn-prev.btn-sm.btn-outline-secondary.btn",
        nextSelector: ".btn-next.btn-sm.btn-outline-secondary.btn",
    },

    {siteName: "真白萌",
        url: "^https?://masiro\\.me/admin/novelReading*",
        contentSelector: ".nvl-content.box-body",
        prevSelector: "a:contains('上一话')",
        nextSelector: "a:contains('下一话')",
    },

**Comment by 821938089** [comment]
这应该没有区别吧
你可以直接去翻目录

在设置里打开快速启动

已添加
