### ISSUE TITLE
7.4.5 更新后起点适配失效了

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#24]
https://read.qidian.com/chapter/EkuQ0HeWob8EGYrhBm4H8w2/kJjmjCRnq5JOBDFlr9quQA2/

**Comment by 821938089** [comment]
更新了，看看还有没有问题

**Comment by letterk** [comment]
好了, 快速启动可能有点问题, 哪怕在其他网站也会出现右下角提示无内容
