### ISSUE TITLE
单章节被分为2个页面怎么处理？

### ISSUE THREAD

**Issue by dalu-test** [821938089/MyNovelReader#25]
比如这个网站
第一页 https://www.dubuxiaoshuo.com/book/p1693/565590.html
第二页 https://www.dubuxiaoshuo.com/book/p1693/565590_2.html

他把单章节拆分成了2个页面，第一个页面里没有“下一章”的字样，导致脚本无法分辨，这种怎么处理较好？

PS：这个网站有很多全本是校正过的，而且补充了星号敏感词。所以我经常使用

**Comment by 821938089** [comment]
写站点规则指定上下章元素的选择器

参考：https://github.com/821938089/MyNovelReader/blob/master/src/MyNovelReader/rule/siteExample.js
```js
    {siteName: "独步小说网",
        url: "https?://www.dubuxiaoshuo.com/book/.*?/.*?\\.html",
        exampleUrl: "https://www.dubuxiaoshuo.com/book/p1693/565590.html",

        contentSelector: "#cont-body",
        prevSelector: ".col-md-6.text-center a:first",
        nextSelector: ".col-md-6.text-center a:last"

    },
```
