### ISSUE TITLE
可以增加一个检测起点防盗VIP的功能吗

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#26]
在检测到防盗章的时候, 不启动
我日常的习惯是启动模式是自动

自从有了防盗以后, 正版阅读体验太难受了

**Comment by 821938089** [comment]
想问下为什么要这样，我给防盗章做了适配，用脚本看也没问题啊

**Comment by letterk** [comment]
因为防盗章脚本并不能解决文字错位, 起点在防盗章里添加了仅在显示区域正确, 显示区以外就是类似"多""少"互换. 
脚本只载入一次

**Comment by 821938089** [comment]
ok 现在防盗章会显示无内容，这样就不会进阅读模式了
