### ISSUE TITLE
起点的域名又改了

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#29]
`read` `vipreader`
以前是这两个子域名, 现在统一改成了`www`

**Comment by 821938089** [comment]
ok 更新了

**Comment by letterk** [comment]
起点在测试新版内容页, 格式全乱了

**Comment by 821938089** [comment]
没有吧，我这里显示很正常啊

他那个新版阅读页巨难进，我点那个新版按钮，页面刷新了还是旧版的，有时候刷新一下突然进得去，再刷新一下又回到旧版了，我都无语了。。。

**Comment by letterk** [comment]
可能是内测推送的, 我这里是直接进新版, 退回旧版用的还是`read`域名, 然后下一页依然是新版的`www`就会格式错乱
可以先观察几天, 等他稳定了再改

**Comment by JasonEX** [comment]
我这边是稳定刷出新版了，目前简单替换了一下规则：
旧版的保留了原来的reader和vipreader域名，新版的临时用的下面的
```
    {siteName: '起点新版-阅文-202305',
      url: '^https?://(?:www)\\.qidian\\.com/chapter/.*',
      exclude: ' /lastpage/',
      bookTitleSelector: 'a.text-s-gray-900',
      titleSelector: '.text-1\.3em',

      prevSelector: '.nav-btn-group a.nav-btn:nth-child(1)',
      nextSelector: '.nav-btn-group a.nav-btn:nth-child(3)',
      indexSelector: '.nav-btn-group a.nav-btn:nth-child(2)',
```

**Comment by letterk** [comment]
> 



> 我这边是稳定刷出新版了，目前简单替换了一下规则： 旧版的保留了原来的reader和vipreader域名，新版的临时用的下面的
> 
> ```
>     {siteName: '起点新版-阅文-202305',
>       url: '^https?://(?:www)\\.qidian\\.com/chapter/.*',
>       exclude: ' /lastpage/',
>       bookTitleSelector: 'a.text-s-gray-900',
>       titleSelector: '.text-1\.3em',
> 
>       prevSelector: '.nav-btn-group a.nav-btn:nth-child(1)',
>       nextSelector: '.nav-btn-group a.nav-btn:nth-child(3)',
>       indexSelector: '.nav-btn-group a.nav-btn:nth-child(2)',
> ```

今天我这里又稳定刷出旧版, 分人群测试

**Comment by JasonEX** [comment]
估计分地区吧，我是游客模式访问的，换了浏览器也一样，手机上的也换了新版，感觉很不稳定

**Comment by JasonEX** [comment]
另外，滚动模式下的上下页URL我没找到，上面能用的得是章节模式

**Comment by letterk** [comment]
起点简直有病, 翻几页一会儿变新版, 一会儿又变回旧版. 现在真的是pc端都是下等人, 没人在乎用户体验

**Comment by 821938089** [comment]
起点有可以滚动翻页，可以先用那个

**Comment by letterk** [comment]
好像新版已经稳定了, 目前都没刷到旧版了

**Comment by 821938089** [comment]
已更新

**Comment by letterk** [comment]
新版的未订阅VIP, 在自动模式会当成普通的处理
![Snipaste_2023-05-30_14-00-16](https://github.com/821938089/MyNovelReader/assets/9822709/f0247d9e-c5da-42bc-8f45-6a517c44cc37)

**Comment by 821938089** [comment]
好了

**Comment by letterk** [comment]
公众章节还是有问题
载入下一章的时候

**Comment by letterk** [comment]
奇怪, 一会儿又正常了, 估计起点又在改什么东西, 看来要多观察下

**Comment by JasonEX** [comment]
关于起点的两个请求：

1. 能把起点移动网站加上吗，我试了一下，应该是可以直接套用新版规则的，所以直接在域名那里把*://m.qidian.com/chapter/*/*加上，规则写成(m|www)应该就可以，主要原因是起点移动版现在没有滚动了比较烦，有条件的话可以麻烦测试一下，我间歇性地发现过下一章加载出问题，但是刷新又好了，没发现原因。
2. 起点的异体字能处理一下吗，有时候会看到奇怪的你、个等等，这个应该需要收集一下

**Comment by 821938089** [comment]
@JasonEX  已更新
