### ISSUE TITLE
[功能需求]自动启用脚本功能

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#3]
默认打开脚本是靠记忆, 这个其实没起到作用, 因为需要保存书签, 最后必然会退出来. 每次操作就是打开章节, 点进入, 看完点退出. 这实际上多了一个不必要的操作步骤. 
如果改变成自动启用, 那么每次就是打开章节, 看完退出. 流程更简化

我目前自改是把设置里的那个强制手动启用, 给改成了强制自动启用
而强制手动启用, 我暂时没想到是在那种场景下使用

---

另外针对起点vip, 因为起点的书签是自动保存的. 就产生了一个问题, 有些作者写的一些公告之类的非章节内容. 我只想看看内容, 但并不想让他保存, 这样会打乱我的书签. 
以前我可以通过上面这个自动启用阅读脚本, 直接在打开章节的时候进入, 这个时候起点保存书签的js就还没运行. 
但起点目前vip内容又是通过js后加载的, 老脚本不会等待所以看不了vip了. 而新脚本等待内容载入的同时, 也让保存书签的js运行了. 这样我每次看一些作者公告就会打乱我的书签, 不知道有没有办法改进下

**Comment by 821938089** [comment]
更新了，试下怎么样

**Comment by letterk** [comment]
自动启用可用

**Comment by letterk** [comment]
![Snipaste_2022-05-24_10-52-19](https://user-images.githubusercontent.com/9822709/169939432-eab86a4d-5567-440e-b6b9-a5cff16280b6.png)
我点开一零六章
![Snipaste_2022-05-24_10-52-26](https://user-images.githubusercontent.com/9822709/169939429-ba86202f-4581-44e0-9925-58eadf4805a7.png)
书签给我保存在了一零七章

---

老作者有个遗留问题, 脚本目前是会在进入的时候加载当前章节并缓存下一章节. 他曾经准备写个切换的设置, 只是施工到一半还没填坑. 
![图片](https://user-images.githubusercontent.com/9822709/169939924-14ba99e1-fffa-46e4-9dce-ba10c1746b8f.png)

**Comment by 821938089** [comment]
更新了，加了个预载下一页的设置

**Comment by letterk** [comment]
取消了预载下一页, 起点vip就无法加载下一章了

**Comment by 821938089** [comment]
我这里测试是正常的
麻烦看看最下方的加载条有说什么提示信息吗？
或者看看控制台有什么报错之类的

**Comment by 821938089** [comment]
我尝试修复了一下，你更新一下看看行不行

**Comment by letterk** [comment]
可以了, 确实是高度计算的问题, 我设置里是比较小只有200px, 因为以前有预载入, 实际上这个功能. 距离底部高度载入是无效的

**Comment by letterk** [comment]
起点使用`LBF.js`来做页面交互的功能, 里面包括自动保存书签
可不可以在进入脚本的时候屏蔽掉他

**Comment by 821938089** [comment]
脚本屏蔽不了，你可以用adblock之类的扩展来屏蔽

**Comment by letterk** [comment]
![图片](https://user-images.githubusercontent.com/9822709/170007292-218d0daf-8ca4-4125-bda4-538b6f8f82eb.png)
firefox浏览器

**Comment by 821938089** [comment]
能否提供一下具体浏览页面的地址？

**Comment by 821938089** [comment]
检查一下浏览器的字体设置是否和我的一样
![image](https://user-images.githubusercontent.com/8674809/170019346-213dce1e-bef9-40b5-99ed-f060d75d08d3.png)

**Comment by letterk** [comment]
最小字号我设置的14

**Comment by 821938089** [comment]
按钮字体大小为12px

**Comment by letterk** [comment]
我想起来之前改过老脚本的这个按钮, 稍微改成了椭圆一点
![图片](https://user-images.githubusercontent.com/9822709/170022119-77a6ef66-cb7a-4459-acb1-6bcdeda9f663.png)
刚好挤下了四个14px的字

**Comment by letterk** [comment]
暂时没发现别的啥问题了, 今天开始正式用新脚本, 有问题会继续反馈的
