### ISSUE TITLE
希望可以再修复一下起点中文

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#37]
下一页的时候就会格式错乱
奇怪的是少部分书没问题, 大部分都有问题

**Comment by 821938089** [comment]
没遇到，哪本书有问题，发一下章节地址吧
格式错乱是怎样的

**Comment by letterk** [comment]
https://book.qidian.com/info/1035890230/#Catalog
随便找一本书都是错乱的
![图片](https://github.com/821938089/MyNovelReader/assets/9822709/0c9b617d-0863-4da2-95ee-b14a75245e82)

**Comment by letterk** [comment]
![图片](https://github.com/821938089/MyNovelReader/assets/9822709/48de27f8-28b6-4eee-8863-193a37f17a75)

**Comment by 821938089** [comment]
你是不是开了快速启动，你把这个关了就可以了

**Comment by letterk** [comment]
![图片](https://github.com/821938089/MyNovelReader/assets/9822709/2b760d71-3a09-499f-a86d-3085c045bc11)
快速启动一直都关着的

**Comment by letterk** [comment]
如果开了快速启动, 在起点直接无法使用脚本

**Comment by 821938089** [comment]
更新了，看看好了没

**Comment by letterk** [comment]
还是不行, 我好像找到原因了
是启动模式-自动出了问题
如果改成手动就好了
这个要修一修

**Comment by 821938089** [comment]
这个修不了，是启动太快导致的问题，好像只有firefox有问题，我用chrome试不出来这个问题
我直接加个延迟吧

**Comment by letterk** [comment]
> 这个修不了，是启动太快导致的问题，好像只有firefox有问题，我用chrome试不出来这个问题 我直接加个延迟吧

我就是firefox, 这样加个延迟也行

**Comment by 821938089** [comment]
已经加了，你重新安装一下脚本就行
