### ISSUE TITLE
这个站点自动加载下一章功能不正常，请指点一下原因

### ISSUE THREAD

**Issue by atest1** [821938089/MyNovelReader#46]
https://www.fkxs.net/241_241951/117822179.html
脚本添加// @include        *://www.fkxs.net/*/*.html
每章分两页，第1章开始的话自动加载到第2章 【双截龙】(第1页/共2页)就认为是最后一章停止了；
第2章 【双截龙】(第2页/共2页)的话加载到第3章 【通辽狠人】(第1页/共2页)停止；
第3章 【通辽狠人】(第1页/共2页)直接就停止了，没有加载下一章。
这个逻辑让我很奇怪，页面结构很简单，自己试着写了一个站点规则：
      {siteName: "逛笔趣阁小说网",
          url: "https?://www\\.fkxs\\.net/.*/.*\.html",
          exampleUrl: 'https://www.fkxs.net/241_241951/117822179.html',
          titleSelector: '.bookname h1',
          contentSelector: ".content",
          nextSelector: '.bottem2 a:nth-child(4)',
          prevSelector: '.bottem2 a:nth-child(2)',
          indexSelector: '.bottem2 a:nth-child(3)',
      }
添加了和没添加一样

**Comment by 821938089** [comment]
脚本有点问题，已修复

**Comment by atest1** [comment]
> 脚本有点问题，已修复

赞神速！
