### ISSUE TITLE
自动翻页后, 退出脚本总是会停留在底部

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#5]
目前一个页面, 进入脚本和退出脚本, 大概会在相似的高度. 不过来回进出, 每次高度都会往下偏移一些. 

自动翻页到下一章后, 不管第二章停留在那里, 退出后一定会在整个页面的底部. 应该是高度计算成了多章节总高度

保持相似高度这个功能是否有必要? 脚本内的字体大小, 内容排版和原网页并不相似. 很难保证准确位置.

**Comment by 821938089** [comment]
这个高度是浏览器记忆的，如果你想要到顶部我可以改改，在退出脚本前滚动到顶部。

**Comment by letterk** [comment]
还发现了个新问题
设置距离底部1200px加载下一页, 触发时居然会页面会自主滚动到底部进行加载, 而不是在后台加载
之前我设置的是400, 每次看到结尾就会有怪异的抖动. 我才设置成1200试试, 我的屏幕视野阅读页面在1000px左右. 就发现了这个自动往下拉的问题

**Comment by 821938089** [comment]
脚本已更新，看看怎么样

**Comment by letterk** [comment]
滚动加载ok了
退出的时候, 滚动到顶部, 有点怪, 是先在脚本里滚到顶部再退出的. 给人感知到了. 总有种章节错乱的感觉

**Comment by 821938089** [comment]
查了一下用别的方法阻止浏览器记忆滚动高度
脚本已更新

**Comment by letterk** [comment]
可以了, 之前那个改进方式, 在退出后, 如果F5刷新页面, 直接退回到置顶的那章. 
现在这样很好
