### ISSUE TITLE
章节名被去除

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#51]
`https://www.xiaoshuting.la/8/8001/13335125.html`
下一章翻页的时候, 这个网站的章节名会被去除, 历史记录也不能正确的记录

**Comment by 821938089** [comment]
写个站点规则
设置`noSection: true`就行了

**Comment by letterk** [comment]
我看到你修改的地方, 之前是因为匹配的是http, 所以实际上站点规则没生效对吧

**Comment by 821938089** [comment]
嗯，以后遇到这种情况你自己写个站点规则就行
