### ISSUE TITLE
起点移动版验证码

### ISSUE THREAD

**Issue by JasonEX** [821938089/MyNovelReader#56]
今天浏览起点移动版，突然频繁跳出来验证码，并且在多次返回验证后，直接禁止访问了一段时间，不知道能不能尝试解决一下

**Comment by 821938089** [comment]
我翻了几十章，没跳验证码
现在起点不需要用脚本来看了吧，都是支持滚动翻页的啊

**Comment by JasonEX** [comment]
我试过没进阅读模式，但是也跳了验证码，也可能是ip问题或者别的什么原因，这个issue先挂一下，我再观察十天看能复现不。

**Comment by JasonEX** [comment]
似乎是IP问题，不再复现
