### ISSUE TITLE
双引号分行反馈

### ISSUE THREAD

**Issue by lkdhyl** [821938089/MyNovelReader#6]
“”内的文本遇到！？会自动另起一行，怎么让它不分行

**Comment by 821938089** [comment]
你是想让双引号内的内容全部都在一行吗？
还有想调查一下你对 `引号内的长内容该如何分段？` 这个问题有什么好的想法？

**Comment by lkdhyl** [comment]
如果是那种对话特别多的小说，作者没有写出对话角色的，没说完分行会混淆读者对话内容

**Comment by 821938089** [comment]
脚本已更新
另外增加了一个内容标准化的开关设置，感觉不好用的话就可以关了
