### ISSUE TITLE
Add a site

### ISSUE THREAD

**Issue by Kaizo2004** [821938089/MyNovelReader#60]
Can this site be added:

********

I tried adding it but there were many problems

**Comment by 821938089** [comment]
added in 7.7.3

**Comment by Kaizo2004** [comment]
Thank you, brother. Can you delete the request? The site owner is always hanging out here xD

**Comment by Kaizo2004** [comment]
Can't download the next chapter automatically?

**Comment by Kaizo2004** [comment]
Thank you very much

**Comment by Kaizo2004** [comment]
Sometimes it doesn't load the next chapter in advance, is this a problem with the site itself?

**Comment by Kaizo2004** [comment]
The next chapter does not appear, every time it says "已到达最后一页..."

Even though I'm only in the first chapter

**Comment by 821938089** [comment]
Tried to fix it, try the latest version.

**Comment by Kaizo2004** [comment]
Thanks for your hard work, I hope that you will add this site to novel-downloader  in the future

Because downloading in txt format does not work on this site
