### ISSUE TITLE
正文居中建议

### ISSUE THREAD

**Issue by meinaOfficial** [821938089/MyNovelReader#65]
脚本运行后，内容靠左，只能调节正文宽度，不能设置正文在屏幕中左右居中，或者增加一个左边空白。建议增加功能，谢谢大佬。

**Comment by 821938089** [comment]
把左边的章节列表关掉就可以居中了

**Comment by meinaOfficial** [comment]
谢谢！如你所言，确实可以居中了。维护脚本辛苦了！
发件人: ***@***.***>
发送时间: 2024年2月15日 19:31
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [821938089/MyNovelReader] 正文居中建议 (Issue #65)


把左边的章节列表关掉就可以居中了

―
