### ISSUE TITLE
UU看書換域名了

### ISSUE THREAD

**Issue by zhigk** [821938089/MyNovelReader#68]
新域名https://www.zhaoshuyuan.com/#gsc.tab=0
因為這原因無效了

**Comment by 821938089** [comment]
已更新

**Comment by zhigk** [comment]
![QQ截图20240313135800](https://github.com/821938089/MyNovelReader/assets/54781313/13bebd23-cf64-4953-9f80-ff8434c2d2ba)剛進去是會顯示已啟用但無效果，重整網頁後就會直接消失

**Comment by 821938089** [comment]
好了，你再重新安装一下

**Comment by zhigk** [comment]
剛剛去重弄了一下…嗯，變成顯示啟用著但無效果，我在想是甚麼問題

**Comment by 821938089** [comment]
截图看看

**Comment by zhigk** [comment]
啊、憨了，忘記要按右下角的閱讀模式了，打擾了xd
