### ISSUE TITLE
简繁转换质量不佳

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#7]
`乾元剑宗`
乾 -> 干

**Comment by 821938089** [comment]
换了个繁简转换表，测试了一下这个词已经不会误替换了
另外如果以后还遇到这种问题我估计也解决不了了，因为我找不到更好的词库了
建议手动进行替换，或者使用浏览器的翻译功能来进行繁简转换
脚本已更新

**Comment by letterk** [comment]
现在有些网站, 整体简体, 中间夹杂很多繁体. 看着极其别扭别扭.
今天还遇到了一个莫名其妙的问题, 我看到了繁体, 退出排查原文, 发现原文是简体, 重新进入依然是简体, 查看设置, 简繁转换是关闭. 太奇怪了, 无法复现这个问题. 
另外简繁转换这个模块能不能改成引入. 目前也不是实时转换, 依然需要刷新, 代码还臃肿了几百k.
