### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by meinaOfficial** [821938089/MyNovelReader#71]
不小心按到TAB键了，然后正文直接跳到下一章了。打游戏空闲出来看书容易误触。建议屏蔽掉这个键位。
脚本那个替换对标题不起作用。刚设置好那一章有用，然后就原形毕露不在替换了
还有就是69书吧已经不太行了，有没有推荐的啊？
拜谢大佬接手这个脚本，感恩！

**Comment by 821938089** [comment]
tab问题已修复
替换标题可以在站点规则里写
目前最好的只有69书吧
现在盗版越来越难了，建议转番茄之类可以免费看的，多找找还是有不少好看的

**Comment by meinaOfficial** [comment]
> tab问题已修复 替换标题可以在站点规则里写 目前最好的只有69书吧 现在盗版越来越难了，建议转番茄之类可以免费看的，多找找还是有不少好看的

站点规则哪里让看Rule.sp什么的，代码我看不懂……太高看我了，太麻烦就算了。
脚本跟原作者做点区别吧，那个booklink那个可以去了，基本没人再用了，而且那个很久不维护了，以后功能差别越来越大，区别开顺便挂在那个脚本网站上吧。我看原作者还在GitHub活跃，但是脚本好久没管了，建议直接接受这个项目吧，我看他心思也不再这个上面了。

**Comment by 821938089** [comment]
我主要自用，这些还是算了
翻翻评论区还是可以找到这里的
