### ISSUE TITLE
无法获取下一页，请手动点击 

### ISSUE THREAD

**Issue by meinaOfficial** [821938089/MyNovelReader#72]
有时候网不好 就会出现无法获取下一页下一章的情况，能不能直接脚本里面多重复请求几次？要不然还要手动点击，一刷新左边目录历史章节就没了。还要重新按c居中。麻烦大佬看看能改吗？
拜谢！

**Comment by 821938089** [comment]
有重试
目录可以在设置里隐藏

**Comment by 821938089** [comment]
打开开发者工具，把日志发一下吧

**Comment by meinaOfficial** [comment]
![屏幕截图 2024-04-11 160723](https://github.com/821938089/MyNovelReader/assets/122218563/9be72c91-33a2-430d-9f62-f165c9a10789)

是这个吗？，感觉请求间隔太短，次数太少。

**Comment by meinaOfficial** [comment]
我平时代理用的比较多，所以网络有时候不太稳定

**Comment by 821938089** [comment]
这个没办法解决，建议换个稳定点的代理或者直接不用，我试了下这个网站可以直接访问的

**Comment by meinaOfficial** [comment]
行吧
