### ISSUE TITLE
章节名空白

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#73]
[https://www.ptwxz.org/ptwx/57621/15733057.html](url)
![image](https://github.com/821938089/MyNovelReader/assets/9822709/3f83940c-fe38-47a5-9d39-cafacc70ddd0)

脚本是识别到了标题的, 但不知为何就一个地方不显示

**Comment by 821938089** [comment]
脚本自动识别到的书名有问题，导致章节名去除书名的时候直接变成空了
