### ISSUE TITLE
69书吧阅读模式问题

### ISSUE THREAD

**Issue by smdx** [821938089/MyNovelReader#74]
你好，在69书吧 https://69shux.com 进入阅读模式后会出现广告拦截工具提示：
“系统检测到您可能开启了广告拦截工具，可能造成内容不完整，请将本站加入白名单或关闭广告拦截工具后刷新本页！”
试过把去广告插件ub关闭还是会出现这段文字，如果不进入阅读模式直接阅读就没有。

![2024-04-21_114907](https://github.com/821938089/MyNovelReader/assets/9279217/cee1f23e-1467-4e8c-8c62-14fddd4ad628)

**Comment by smdx** [comment]
如果在ub添加拦截
69shux.com##p:nth-of-type(32)
69shux.com##p:nth-of-type(58)
括号的数值会一直变，改成（n+2）会阻止所有元素文字内容都没有了，这个应该怎么写规则才行？谢谢

**Comment by 821938089** [comment]
增加了这个站点的规则，你更新一下脚本就可以了

**Comment by smdx** [comment]
好的，谢谢
