### ISSUE TITLE
铅笔小说无法加载下一页

### ISSUE THREAD

**Issue by smdx** [821938089/MyNovelReader#77]
大佬你好，铅笔小说无法加载下一页，开启阅读模式后当前章节最下方显示：已到达最后一页...

站点：
https://www.23qb.com/book/14857/11524489.html
![2024-04-28_140509](https://github.com/821938089/MyNovelReader/assets/9279217/93202096-117d-4e85-a834-8f36d1e7ad80)

**Comment by 821938089** [comment]
已更新

**Comment by smdx** [comment]
感谢，更新后正常加载了。
