### ISSUE TITLE
简繁转换bug

### ISSUE THREAD

**Issue by letterk** [821938089/MyNovelReader#8]
https://www.69shu.com/txt/40819/28972399

![图片](https://user-images.githubusercontent.com/9822709/171987560-3814a9ed-f703-4e73-bfad-ce09c07a6ce8.png)

看到了繁体, 退出检查原文为简体, 重进阅读为简体, 查看设置简繁转换为关闭. 触发这个bug的可能是在自动翻页的时候

另外可不可以把简繁转换模块改成引入, 打开功能再引入? 臃肿了几百k

**Comment by letterk** [comment]
好像已经在6.9.5修复了
我这Tampermonkey, 38小时了也不给我更新

**Comment by 821938089** [comment]
> 另外可不可以把简繁转换模块改成引入, 打开功能再引入? 臃肿了几百k

不能，实现这个功能需要服务器来动态加载代码。
目前主要存在以下两个问题：
1、国内没有可以自由托管JS的cdn，国外的因为墙的问题服务不可靠。
2、数据缓存和更新问题，不可能每次打开脚本都要重新加载一遍吧。

<hr>

我觉得把东西都内联到脚本里面挺好的，这样就不会遇到网页的内容安全策略限制或者跨域限制等问题。
而且这样还不用依赖服务器，可以减少脚本因为服务器挂掉而无法使用的可能性。

<hr>

自动翻译应该是你的网页的语言设置成了英语导致的，你把代码可以改成 `<html lang="zh-CN">` 就不会触发自动翻译了。
