### ISSUE TITLE
省略号分隔行会被自动替换

### ISSUE THREAD

**Issue by MAN-GOR** [821938089/MyNovelReader#81]
如题，用作分隔行的省略号在进入阅读模式后会被自动替换掉。
受影响章节：https://www.qidian.com/chapter/1039071756/782678965/
例子：
进入阅读模式前：
「
　　他现在，内心很慌很乱。

　　…

　　放下手机。
」
进入阅读模式后：
「
　　他现在，内心很慌很乱。

　　放下手机。
」

**Comment by 821938089** [comment]
已更新脚本
