### ISSUE TITLE
依赖CDN网址域名更换，旧域名会被adguard等软件过滤导致无法加载脚本依赖

### ISSUE THREAD

**Issue by infseers** [821938089/MyNovelReader#85]
受org域名备案影响主域名更新为 staticfile.net , org老域名不再维护请用户尽快更换为net。

# 需要更新的域名
// @require        https://cdn.staticfile.org/vue/2.2.6/vue.min.js
// @require        https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js
// @require        https://cdn.staticfile.org/underscore.js/1.7.0/underscore-min.js
// @require        https://cdn.staticfile.org/keymaster/1.6.1/keymaster.min.js
// @require        https://cdn.staticfile.org/crypto-js/4.1.1/crypto-js.min.js
# 修改后
// @require        https://cdn.staticfile.net/vue/2.2.6/vue.min.js
// @require        https://cdn.staticfile.net/jquery/2.1.1/jquery.min.js
// @require        https://cdn.staticfile.net/underscore.js/1.7.0/underscore-min.js
// @require        https://cdn.staticfile.net/keymaster/1.6.1/keymaster.min.js
// @require        https://cdn.staticfile.net/crypto-js/4.1.1/crypto-js.min.js

**Comment by 821938089** [comment]
域名被广告屏蔽扩展过滤是因为这个CDN被曝存在供应链攻击，有什么国内可替代的CDN推荐吗，感觉全军覆没了。
https://www.tjsky.net/news/992

**Comment by infseers** [comment]
> 域名被广告屏蔽扩展过滤是因为这个CDN被曝存在供应链攻击，有什么国内可替代的CDN推荐吗，感觉全军覆没了。 https://www.tjsky.net/news/992

才了解Polyfill供应链攻击，改用改用由Fastly或Cloudflare，个人推荐https://cdnjs.cloudflare.com/，国内应该能直连

// @require https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.6/vue.common.js
// @require https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js
// @require https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js
// @require https://cdnjs.cloudflare.com/ajax/libs/keymaster/1.6.1/keymaster.min.js
// @require https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js

**Comment by 821938089** [comment]
已更新脚本
