### ISSUE TITLE
小问题想请教

### ISSUE THREAD

**Issue by piedfallow** [821938089/MyNovelReader#9]
大大不好意思，想请教两个问题
1. 我安装好最新版本6.9.6，在晋江阅读模式无法开启，不是很确定哪边有问题，想请问如何解决(我使用的浏览器为firefox，chrome也无法开启)
2. 有几次偶尔成功开启了阅读模式，但是内容却是不完整的(主要是VIP章节，非VIP章节我没有尝试)，想请教如何解决这个问题

**Comment by 821938089** [comment]
> 我安装好最新版本6.9.6，在晋江阅读模式无法开启，不是很确定哪边有问题，想请问如何解决(我使用的浏览器为firefox，chrome也无法开启)

无法开启时什么意思？是没有阅读模式的按钮还是点击按钮没有反应，还是点击按钮后按钮文字变成 `无内容` ？

> 有几次偶尔成功开启了阅读模式，但是内容却是不完整的(主要是VIP章节，非VIP章节我没有尝试)，想请教如何解决这个问题

发个图和章节地址看看具体是什么情况

**Comment by piedfallow** [comment]
无法开启的部份是点了完全没反应，现在无法开启阅读模式所以无法截图，下面的网址是我有购买VIP的其中一本书，给大大参考，影片解释无法开启的部份，文章为网址文章
http://www.jjwxc.net/onebook.php?novelid=6378166

https://user-images.githubusercontent.com/88279588/172042575-a1e53b1f-52d4-4d14-8059-54ebec34f77f.mp4

**Comment by 821938089** [comment]
你要在章节内容页进入，不是目录页
例如 http://www.jjwxc.net/onebook.php?novelid=6378166&chapterid=1

**Comment by 821938089** [comment]
发了个新版本修复了一下在目录页显示了阅读模式按钮的bug

**Comment by piedfallow** [comment]
https://user-images.githubusercontent.com/88279588/172043151-d944dd38-09d7-45ec-9d78-148f42c13718.mp4

我有再试了一下新版本，仍旧无法解决问题，附上影片给大大参考

**Comment by 821938089** [comment]
你打开一下浏览器的开发人员工具看一下控制台输出了什么内容
右键->检查 或 按F12会有显示

**Comment by piedfallow** [comment]
![1](https://user-images.githubusercontent.com/88279588/172043484-619330f3-2df4-43ca-a45b-07891364c46f.png)

**Comment by piedfallow** [comment]
我不是很懂这个，所以截图给大大看，非常不好意思麻烦您了

**Comment by 821938089** [comment]
尝试禁用其他拓展只保留油猴看看
还有控制台下面还有东西吗

**Comment by 821938089** [comment]
![image](https://user-images.githubusercontent.com/8674809/172044007-18294cdd-5490-465d-8d3d-8438f2f00552.png)
你把控制台点成这样看看，你的控制台好像把错误给过滤掉了

**Comment by piedfallow** [comment]
我目前尝试了几个状况
1.关闭所有扩充程式，发现是跟我的其中一个右键复制的扩充程式冲突了，关掉后可以正常进入以及退出阅读模式(如图)
![1](https://user-images.githubusercontent.com/88279588/172044307-ecf45b49-a979-4755-81c8-b93fde680f54.png)
这张图是完全没有关闭的状态
![5](https://user-images.githubusercontent.com/88279588/172044328-ec2f3809-ad98-4374-8c68-51d0290b4b03.png)
这张图是完全关闭除了油猴以外的扩充程式
![4](https://user-images.githubusercontent.com/88279588/172044353-5b00bfae-7788-4c9d-af8b-ddf3b6814c80.png)
这是原文的状态
![4](https://user-images.githubusercontent.com/88279588/172044360-22a795c1-754c-4a17-a6f7-556959b259e0.png)
这是进入阅读模式后，明显内容有缺失
![6](https://user-images.githubusercontent.com/88279588/172044416-080e89c8-97a8-45a0-8f0f-bb966bc1df34.png)
这是进入阅读模式时的后台状况

**Comment by 821938089** [comment]
图片是不是发错了，进入阅读模式的图不是这样的吧，界面不该是这样的

**Comment by piedfallow** [comment]
是的，图片有问题我分开发好了
![1](https://user-images.githubusercontent.com/88279588/172044756-3aa48c61-c00b-4d71-a64c-35b1e5c05536.png)
这张是完全没有关闭时的状态

**Comment by piedfallow** [comment]
![5](https://user-images.githubusercontent.com/88279588/172044795-f317968e-c48b-49c1-b4ab-ac4e5790f7ba.png)
这张是关闭后非阅读模式下的状态

**Comment by 821938089** [comment]
直接截图进入阅读模式后的界面和控制台就好了，或者录个视频

**Comment by piedfallow** [comment]
![2](https://user-images.githubusercontent.com/88279588/172044910-c66a325e-f2a6-4682-b038-21a103d46a6b.png)
这个是VIP章节进入阅读模式后的控制台

**Comment by piedfallow** [comment]
![3](https://user-images.githubusercontent.com/88279588/172044948-2a09fc24-9573-4121-9298-8874ee4a32e5.png)
界面长这样

**Comment by piedfallow** [comment]
![4](https://user-images.githubusercontent.com/88279588/172045015-92590c08-3971-4db1-88e0-cd72a821c00b.png)

![1](https://user-images.githubusercontent.com/88279588/172045019-eb0cd36d-5649-4a98-a53e-846d5a9e2cda.png)

这是非V章节界面与控制台

**Comment by 821938089** [comment]
右上角设置 -> 内容标准化 取消勾选
看看内容有没有问题

**Comment by piedfallow** [comment]
![1](https://user-images.githubusercontent.com/88279588/172045585-4a4fff67-5fdd-43e5-907a-00f8114e83fb.png)
![2](https://user-images.githubusercontent.com/88279588/172045589-79cad7dc-7f64-4641-ab8f-19fe9fc2e6f5.png)

**Comment by piedfallow** [comment]
取消后内容只剩一行

**Comment by 821938089** [comment]
账号能借我让我来测试一下吗
实在想不到是什么问题导致的了了，想看一下章节的页面结构

**Comment by piedfallow** [comment]
可以的，我要如何給您?私信嗎?

**Comment by 821938089** [comment]
有 Telegram 吗
https://t.me/Grphk0

**Comment by 821938089** [comment]
修好了，你试试
