### ISSUE TITLE
页宽问题

### ISSUE THREAD

**Issue by EaglePPP** [821938089/MyNovelReader#91]
在进去点击按钮进入阅读模式后，之前在菜单中设置的页宽不会被应用，需要手动重新修改后才会应用（原版也一直存在的问题

**Comment by 821938089** [comment]
复现不了，你录个视频看看

**Comment by 821938089** [comment]
这个设置是有单位的，你把单位都删了，所以才会有问题
通常使用单位：
字体行宽px
行高段高em
